jobs:
- job: Publish
  pool:
    name: default
    demands:
      agent.name -equals ubuntu-build-server
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
  - script: yarn install
  - task: Npm@1
    inputs:
      command: publish
      publishRegistry: useExternalRegistry
      publishEndpoint: npmjs